### ISSUE TITLE
Will you open source code and weights? What license is used for open source

### ISSUE THREAD

**Issue by libai-lab** [Zheng-Chong/CatVTON#1]
Will you open source code and weights? What license is used for open source

**Comment by Zheng-Chong** [comment]
Thank you for your attention to this project. We are planning to open-source our code and weights under the CC BY-NC-SA license within a few weeks.

**Comment by Zheng-Chong** [comment]
Our weights and code for inference and app have been release 😄！

**Comment by Zheng-Chong** [comment]
Thank you for pointing this out. I am not very familiar with open source protocols. Can you suggest some software protocols that can restrict commercial use?

**Comment by devingfx** [comment]
> some software protocols that can restrict commercial use?

1) I bet this is a translation issue, but there is no "software protocols" that can restrict a use... Probably you mean: "software licence" !?

2) What kind of commercial restiction do you have in mind?
- Restrict the selling of code ?
  => GPL or another copyleft licence
- Restrict the selling of weights ?
  => not sure what licence ? maybe some around databases
- Restrict the selling of an access to a self-hosted demo app ?
  => go to private licences (no more open-source nor publicly accessible)
- Restrict the selling of code/weights/demo derivatives ?
  => GPL or another copyleft licence
- Restrict the selling of output images ?
  => not sure this is possible (imagine GIMP restricting the use of images produced by it) or maybe go to private licences (no more open-source nor publicly accessible)
  BTW any restriction comes with a mean of verifying it, if you can't figure out for sure if an image on a random e-commerce is made by your software, you won't be able to suit anyone on court...
