### ISSUE TITLE
Problems when Face Printed on clothes

### ISSUE THREAD

**Issue by mateng0716** [Zheng-Chong/CatVTON#11]
![微信截图_20240731172305](https://github.com/user-attachments/assets/029c6030-1ce9-438e-af64-f931fe00497a)

it seems to have some problems when the clothes is printed with a HEAD or FACE ,  it distorted easily~

**Comment by Zheng-Chong** [comment]
Perhaps adjusting the random seed could improve performance. However, even though this is our goal, CatVTON, as a research-oriented project, cannot guarantee the desired outcomes in all situations.

**Comment by Zheng-Chong** [comment]
I tested some clothes with faces and there was no such serious distortion problem, maybe you could provide your test cases to help me see the problem further?
![image-2](https://github.com/user-attachments/assets/d516452a-65e9-4b88-be73-1476a4cdce13)
![image-3](https://github.com/user-attachments/assets/56f733ff-f1d7-4a93-9d12-133ba90d1fc7)
