### ISSUE TITLE
Host the demo on Huggingface Spaces ZeroGPU 

### ISSUE THREAD

**Issue by yvrjsharma** [Zheng-Chong/CatVTON#18]
Hi @Zheng-Chong Congratulations on CatVTON release! Would be great to have the demo up on Huggingface Spaces. We provide GPU grants for interesting projects and paper-implementations, and would be happy to support CatVTON with ZeroGPU (A100s) sponsorship! 

You might need to modify the current gradio code for ZeroGPU Spaces usage, actually. To understand this better, please refer to the usage section of the organization: https://huggingface.co/zero-gpu-explorers.

We also have a step-by-step guide for using the gradio sdk on Spaces: https://huggingface.co/docs/hub/en/spaces-sdks-gradio.

Applying for grants on Spaces is fairly easy using the `Settings` tab of your Space. For more information on how to apply for GPU grants on Spaces, please visit: https://huggingface.co/docs/hub/en/spaces-gpus#community-gpu-grants."

**Comment by Zheng-Chong** [comment]
Thank you very much for the support from the ZeroGPU project !
I will deploy CatVTON to the HuggingFace Space as soon as possible according to your guide!

**Comment by yvrjsharma** [comment]
Awesome, @Zheng-Chong thanks! We can start a shared Slack collab channel for supporting you in the process. If you think that will be helpful, you can let me know, and I'll send an invite.

**Comment by Zheng-Chong** [comment]
That would be great! I do have some questions about Space, please send me an invitation, thank you！

**Comment by Zheng-Chong** [comment]
Thank you for your patient assistance, which has enabled the launch of CatVTON Space. 🥳

**Comment by yvrjsharma** [comment]
Awesome @Zheng-Chong ! Thanks for all the hard work and congratulations on the Spaces release 🥳
