### ISSUE TITLE
Dependencies issues

### ISSUE THREAD

**Issue by cardosofelipe** [Zheng-Chong/CatVTON#2]
Hi, it would be great to try out such project. However the requirements.txt is a bit messed up. Lot's of broken or missing dependencies.
For example, densepose module is nowhere to be found as pip package, as well as detectron2 (this one I installed from git repo).
Can you please do a clean check on your requirements.txt and maybe update readme with an installation section?

Thanks.

**Comment by Zheng-Chong** [comment]
Thank you for raising this issue. We have reorganized the environmental dependencies and provided an [installation guide](https://github.com/Zheng-Chong/CatVTON/blob/main/INSTALL.md). Please test it, and if there are any questions, please do not hesitate to let us know.
