### ISSUE TITLE
 Potential NSFW content was detected in one or more images. 

### ISSUE THREAD

**Issue by yatoubusha** [Zheng-Chong/CatVTON#22]
when i run app.py, i will get this error: A black image will be returned instead. Try again with a different prompt and/or seed.
![image](https://github.com/user-attachments/assets/647c4893-501c-4917-8919-23ca8f1be891)

**Comment by Zheng-Chong** [comment]
Since the training of the base model SD1.5 we use contains NSFW data, we added SafetyChecker to the code to prevent potential NSFW from being displayed.
You can skip it in the code by setting `skip_safety_check=True`, but we don't recommend it.
```
    pipeline = CatVTONPipeline(
        ...
        skip_safety_check=True
    )
```

**Comment by yatoubusha** [comment]
> Since the training of the base model SD1.5 contains NSFW data, we added SafetyChecker to the code to prevent potential NSFW from being displayed. You can skip it in the code by setting `skip_safety_check=True`, but we don't recommend it.
> 
> ```
>     pipeline = CatVTONPipeline(
>         ...
>         skip_safety_check=True
>     )
> ```

Thanks, but why is the frequency of this problem so high? I have tried changing the seed multiple times but it still works like this. Additionally, the official demo webpage cannot be opened. Can you please restart it? Why didn't I encounter this problem frequently when I tried it on the official demo webpage before?

**Comment by Zheng-Chong** [comment]
We used SD's safetychecker directly, the high frequency may be because its settings need to filter potential NSFW as much as possible. The demo was offline on 8.1 and we have restarted it on 8.4.
The safetychecker in the online demo has no difference from the one in the code.

**Comment by yatoubusha** [comment]
> We used SD's safetychecker directly, the high frequency may be because its settings need to filter potential NSFW as much as possible. The demo was offline on 8.1 and we have restarted it on 8.4. The safetychecker in the online demo has no difference from the one in the code.

Thank you very much for your reply. After trying to skip, I was able to generate the image normally, and it is not from nsfw. Perhaps the filtering criteria were set too strictly. The recovery of the web version demo is really good news. Thank you for your open source work.
