### ISSUE TITLE
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

### ISSUE THREAD

**Issue by FahriBilici** [Zheng-Chong/CatVTON#23]
Hello, I am using macOS with silicone chip. I followed installing guide in both comfyui and catvton. but i am getting this error `OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.`

due to this custom nodes import fails.

How can I solve it?

**Comment by Zheng-Chong** [comment]
This project is currently not adapted for M series chips, sorry for that.

**Comment by FahriBilici** [comment]
Can I run it with cpu?

**Comment by Zheng-Chong** [comment]
The M series chip Mac has unified memory. Perhaps the most convenient way is to use our online demo 😂.

**Comment by FahriBilici** [comment]
I am gonna try on google colab than 😂

**Comment by AbdurrahimBalta** [comment]
when it is adapted the m series chip?

**Comment by Zheng-Chong** [comment]
Since Detectron2 and SCHP seem to require CUDA, this makes them difficult to run on a Mac. We are trying to find alternatives so that the projects rely solely on the Pytroch framework, but this will take some time.

**Comment by bhupesh-sf** [comment]
looking forward to this, because I am all mac with apple silicon but dying to try this project out :(
