### ISSUE TITLE
VITON-HD results

### ISSUE THREAD

**Issue by franciszzj** [Zheng-Chong/CatVTON#28]
Thank you for your great work on CatVTON!

I tested the VITON-HD model and generated 512x384 images.
I resized the ground truth to 512x384 and tested SSIM and FID, and found that the metrics are SSIM=0.856 and FID=8.63. This does not match the metrics in the paper.
So, were the metrics in the paper obtained using a "mix model", rather than just the model trained on VITON-HD?

**Comment by Zheng-Chong** [comment]
There is a similar issue before, maybe you can check it. https://github.com/Zheng-Chong/CatVTON/issues/10

**Comment by walkingwithGod123** [comment]
> There is a similar issue before, maybe you can check it. #10之前也有类似的问题，你可以查一下。 #10 The Inference on the specific dataset does not need to use the Mix-task model.对特定数据集的Inference不需要使用Mix-task模型。 For the computation of FID and KID metrics, we utilize [cleanfid](https://github.com/GaParmar/clean-fid); for other metrics, we employ [torchmetrics](https://lightning.ai/docs/torchmetrics/stable/).为了计算 FID 和 KID 指标，我们使用[cleanfid](https://github.com/GaParmar/clean-fid) ；对于其他指标，我们使用[torchmetrics](https://lightning.ai/docs/torchmetrics/stable/) 。 I will put the organization of the eval code on the agenda to help reproduce the results.我会将评估代码的组织提上议程，以帮助重现结果。

Thank you. I would like to ask, during the inference process, which dataset, VITON-HD or DressCode, performs better? DressCode requires filling out an application form, and I don't have an institutional email address. Looking forward to your reply, thank you.

**Comment by Zheng-Chong** [comment]
The calculation of the metrics is obtained by comparing with the original ground truth; generally, the higher the metric, the closer it is to the original data. 
So metrics obtained from different datasets are not comparable.

**Comment by walkingwithGod123** [comment]
> The calculation of the metrics is obtained by comparing with the original ground truth; generally, the higher the metric, the closer it is to the original data. So metrics obtained from different datasets are not comparable.

Okay, I understand, thank you for your reply.

**Comment by Zheng-Chong** [comment]
https://github.com/Zheng-Chong/CatVTON?tab=readme-ov-file#3-calculate-metrics  
Eval code and guidance are provided!
