### ISSUE TITLE
在Windows上通过Gradio使用的本地部署教程！

### ISSUE THREAD

**Issue by WalkingwithAI** [Zheng-Chong/CatVTON#29]
非常感谢[Zheng-Chong]大佬的工作，项目的效果非常出色。我在Windows上使用Gradio的本地部署过程中，遇到了不少问题，包括 #12 的问题，后来通过查阅资料和不断尝试，最终部署成功了。
我出了一期教程，希望能对其他朋友们有所帮助。再次感谢[Zheng-Chong]大佬的工作和开源精神，点赞！！

Windows本地部署教程：
https://www.bilibili.com/video/BV173YueAEdi/?vd_source=6c8b8679b818b05d24c65f49a65eb994

**Comment by Amazon90** [comment]
comfyui custom_nodes dir path: git clone https://github.com/chflame163/ComfyUI_CatVTON_Wrapper.git
cd ComfyUI_CatVTON_Wrapper
pip install -r requirements.txt
Loading Workflow, ComfyUI Manager Install Missing Custom Nodes
git lfs install
git clone https://huggingface.co/risunobushi/catvton_model_lib ComfyUI/models/CatVTON

**Comment by walkingwithGod123** [comment]
> comfyui custom_nodes dir path: git clone https://github.com/chflame163/ComfyUI_CatVTON_Wrapper.gitcomfyui custom_nodes dir 路径： git clone https://github.com/chflame163/ComfyUI_CatVTON_Wrapper.git cd ComfyUI_CatVTON_Wrapper pip install -r requirements.txtpip install -r 要求.txt Loading Workflow, ComfyUI Manager Install Missing Custom Nodes加载工作流程，ComfyUI Manager 安装缺少的自定义节点 git lfs install git lfs 安装 git clone https://huggingface.co/risunobushi/catvton_model_lib ComfyUI/models/CatVTONgit 克隆https://huggingface.co/risunobushi/catvton_model_lib ComfyUI/models/CatVTON

Nice!
