### ISSUE TITLE
agnostic masks

### ISSUE THREAD

**Issue by lxz203000** [Zheng-Chong/CatVTON#3]
Very good work, if I want to test my own models, how can I make agnostic masks?

**Comment by Zheng-Chong** [comment]
I'm not sure what you specifically mean by "test my own models", but we have provided an automated mask generator based on SCHP and DensePose in `[model/cloth_masker.py](https://github.com/Zheng-Chong/CatVTON/blob/60f283baf535a0d3c810772d35ce943127b350e8/model/cloth_masker.py#L155)`. It is very easy to use; you can refer to its usage in `[app.py](https://github.com/Zheng-Chong/CatVTON/blob/60f283baf535a0d3c810772d35ce943127b350e8/app.py#L123)`. If this part is helpful for your research, we would be delighted if you give us appropriate credit.
