### ISSUE TITLE
Comfyui installation is not fully adapted

### ISSUE THREAD

**Issue by Amazon90** [Zheng-Chong/CatVTON#30]
![comfy](https://github.com/user-attachments/assets/6706328c-cabc-4d8f-ac1a-5a72fb0fc657)
The project author did not fully adapt comfyui. When I used manager to install the missing nodes, it prompted No Results.
When I download the zip archive and json workflow in release, I get an error when launching comfyui.
When I opened the installation guide, I found that the installation steps it described could not be followed under the Windows operating system.
https://github.com/Zheng-Chong/CatVTON/blob/main/INSTALL.md

**Comment by Zheng-Chong** [comment]
Our project is **_research-oriented_** and there is no guarantee that our project can run on arbitrary environments.
However, some users have successfully installed it on Windows, and you can refer to their tutorials: 
https://github.com/Zheng-Chong/CatVTON/issues/29
https://github.com/Zheng-Chong/CatVTON/issues/8

**Comment by Amazon90** [comment]
comfyui custom_nodes dir path: git clone https://github.com/chflame163/ComfyUI_CatVTON_Wrapper.git
cd ComfyUI_CatVTON_Wrapper
pip install -r requirements.txt
Loading Workflow, ComfyUI Manager Install Missing Custom Nodes
git lfs install
git clone https://huggingface.co/risunobushi/catvton_model_lib ComfyUI/models/CatVTON
