### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/DressCode/upper_body/agnostic_masks/048402_0.png'  Description:

### ISSUE THREAD

**Issue by CrispyFeSo4** [Zheng-Chong/CatVTON#32]
`ERROR：FileNotFoundError: [Errno 2] No such file or directory: '/DressCode/upper_body/agnostic_masks/048402_0.png'`

I found that the provided `our preprocessed agnostic masks` contains fewer than 1800 masks (upper/lower/dresses are all affected), which causes this error.  How can this be resolved in such a case?

thanks!!

**Comment by Zheng-Chong** [comment]
Hi! I just wrote a script that allowed you to preprocess the agnostic masks by yourself, refer to https://github.com/zheng-chong/catvton?tab=readme-ov-file#1-data-preparation

**Comment by CrispyFeSo4** [comment]
Issue resolved, thank you for your prompt and quick response! Good day!!
