### ISSUE TITLE
Error occurred when I tried to change input width and height!

### ISSUE THREAD

**Issue by miniwa00** [Zheng-Chong/CatVTON#34]
Hi! Thanks for your great work! 

When I don't give any specific width and height value, It works perfectly
But when I tried to change these width and height, the code runs successfully without any warnings or errors, but the result that I've got is just black empty image. (below image)
I think resolutions were changed into given options.

Thanks!

![image](https://github.com/user-attachments/assets/6eca20f1-10aa-429d-843d-418d4c68153d)

**Comment by Zheng-Chong** [comment]
CatVTON's training does not currently accommodate various aspect ratios and resolutions; the 1024 model only produces satisfactory results at a resolution of 1024x768. However, adapting to variable resolutions is on our list of improvements for future development.

**Comment by miniwa00** [comment]
I understand! Thanks for your quick answers ;)

**Comment by miniwa00** [comment]
I wil close it! Thanks again!
