### ISSUE TITLE
缺少SCHP.py

### ISSUE THREAD

**Issue by shenboxy** [Zheng-Chong/CatVTON#35]
[Prompt Server] web root: D:\AI\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.2.27
Skip D:\AI\ComfyUI\custom_nodes\CatVTON module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.
Adding D:\AI\ComfyUI\custom_nodes to sys.path
Could not find efficiency nodes

**Comment by Zheng-Chong** [comment]
Refer to https://github.com/Zheng-Chong/CatVTON/issues/8 for Windows ComfyUI Installation.
