### ISSUE TITLE
VITON-HD inference needs not existing file

### ISSUE THREAD

**Issue by jufilateva** [Zheng-Chong/CatVTON#37]
Hello and thank you for your work!

I've tried to run an inference on VITON-HD that I've downloaded locally. And while inference I see this error:

Traceback (most recent call last):
  File "/home/cuda/CatVTON/inference.py", line 325, in <module>
    main()
  File "/home/cuda/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/cuda/CatVTON/inference.py", line 269, in main
    dataset = VITONHDTestDataset(args)
  File "/home/cuda/CatVTON/inference.py", line 18, in __init__
    self.data = self.load_data()
  File "/home/cuda/CatVTON/inference.py", line 39, in load_data
    assert os.path.exists(pair_txt:=os.path.join(self.args.data_root_path, 'test_pairs_unpaired.txt')), f"File {pair_txt} does not exist."
AssertionError: File /home/cuda/zalando-hd-resized/test_pairs_unpaired.txt does not exist.

I've downloaded it again and rechecked file structure, but there is no test_pairs_unpaired.txt file in VITON-HD dataset. How could I avoud this problem?

**Comment by Zheng-Chong** [comment]
Please check `/home/cuda/zalando-hd-resized/test_pairs_unpaired.txt` in your local folder.
Maybe your local `.txt` name is different, renamed it as `test_pairs_unpaired.txt`.

**Comment by jufilateva** [comment]
![viton0hd test structure](https://github.com/user-attachments/assets/5bddfa05-5467-444f-9705-faefd8dd8db5)
![viton-hd structure](https://github.com/user-attachments/assets/f7bd47f6-857b-40df-9a79-621daab115b2)

There are screens of dataset structure. Could the 'test_pairs.txt' be the file that sould be renamed?

**Comment by Zheng-Chong** [comment]
yes
