### ISSUE TITLE
推理时间不稳定

### ISSUE THREAD

**Issue by zeng121** [Zheng-Chong/CatVTON#42]
我在A10上 推理耗时最快都要20s
我的torch版本是2.1.0

**Comment by Zheng-Chong** [comment]
推理时间和显卡性能、GPU 性能、显卡利用率等参数都有关系，在同样的环境下进行相同数据的推理，推理时间应该是稳定的。
不确定你说的推理时间不稳定具体指什么

**Comment by zeng121** [comment]
感谢你的回答
还有就是我在两台相同配置、相同环境的服务器上跑，唯一的区别是显卡驱动版本不一样，同一张图片跑出了不同的效果。是否跟显卡驱动也有关，我的两台服务器cuda和torch的版本是一样的

**Comment by zeng121** [comment]
> 感谢你的回答 还有就是我在两台相同配置、相同环境的服务器上跑，唯一的区别是显卡驱动版本不一样，同一张图片跑出了不同的效果。是否跟显卡驱动也有关，我的两台服务器cuda和torch的版本是一样的

**Comment by zeng121** [comment]
我之前的算法在两台服务器上跑都没差异，是否这个算法的某个api跟显卡驱动有关？

**Comment by Zheng-Chong** [comment]
> 我之前的算法在两台服务器上跑都没差异，是否这个算法的某个api跟显卡驱动有关？

没有进行过这个方面的测试
