### ISSUE TITLE
Giving bad result ..

### ISSUE THREAD

**Issue by Tanmaypatil123** [Zheng-Chong/CatVTON#45]
I was trying to clone the huggingface space because previous huggingface space crashed because runwayml removed all there open source checkpoints .. when i extracted same code from app.py gradio application and inferenced it in jupyter notebook it gave me some bad results .

@Zheng-Chong 

![image](https://github.com/user-attachments/assets/040e300c-4b09-40eb-ad97-32ef416e7542)

**Comment by Tanmaypatil123** [comment]
the model is changing to many things and making image bad. like face is destroyed in above image .

**Comment by Zheng-Chong** [comment]
This seems to be caused by incorrect settings of Classifier-Free Guidance Scale. CFG should be between 2.5 and 3.5 to achieve better results

**Comment by miniwa00** [comment]
why don't you try more num_inference_steps?

**Comment by Tanmaypatil123** [comment]
Yes I tried reducing cfg value and  it worked .
