### ISSUE TITLE
OSError: runwayml/stable-diffusion-inpainting is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'

### ISSUE THREAD

**Issue by duongngockhanh** [Zheng-Chong/CatVTON#47]
I can't access to runwayml/stable-diffusion-inpainting. Therefore, the model does not work. How can I fix that?
![image](https://github.com/user-attachments/assets/3131fc08-b43b-4aed-b3b3-220c02293d5f)

**Comment by yueool** [comment]
我也是报这个错，可能是因为：https://huggingface.co/runwayml/stable-diffusion-inpainting 现在404造成的

**Comment by Zheng-Chong** [comment]
Runawayml has deleted the original repo, making it impossible to find the model on HuggingFace. The new version of the code has been switched to a forked repo.

**Comment by gilang-bintang** [comment]
@Zheng-Chong what did you use instead?

**Comment by Zheng-Chong** [comment]
> [@Zheng-Chong](https://github.com/Zheng-Chong) what did you use instead?

[https://huggingface.co/booksforcharlie/stable-diffusion-inpainting](https://huggingface.co/booksforcharlie/stable-diffusion-inpainting) is used.
