### ISSUE TITLE
The results are different on Gradio vs Local inference

### ISSUE THREAD

**Issue by AI-P-K** [Zheng-Chong/CatVTON#54]
Hello,

I have installed CatVTON locally, downloaded the repository, created a new anaconda environment. I created a custom dataset that has the following:
1. agnostic-mask -> SCHP 
2. cloth -> original clothing image resized to 1024x768
3. cloth-mask -> SCHP
4. image -> original person image resized to 1024x768
5. image_parse-v3 -> CIHP_PGN
6. openpose_img -> OpenPose
7. opnepose_json -> OpenPose

Original input images:
![dude2](https://github.com/user-attachments/assets/0485dedd-f2e9-491f-b8b7-b7f12362e381) - original person image
![8](https://github.com/user-attachments/assets/97b499a3-0a59-4c1f-a0c7-c55c4fe7699e) - original clothing image

Processed data:
![dude2_mask](https://github.com/user-attachments/assets/61211587-4226-4350-a5f1-eeb00efcbe5b) - agnostic-mask
![8](https://github.com/user-attachments/assets/7767ee9f-45e2-4877-aab3-1d504fa2774f) - cloth-mask
![dude2](https://github.com/user-attachments/assets/0c82c5c2-0296-40b2-8a9e-9d2a0c7b6953) - image_parse-v3 
![dude2_rendered](https://github.com/user-attachments/assets/c85e7c9e-7a46-42a3-8c5f-3ca94a82eff8) - openpose_img
[dude2_keypoints.json](https://github.com/user-attachments/files/16977134/dude2_keypoints.json) - openpose_json 

Results:
![dude2](https://github.com/user-attachments/assets/5529b913-b812-45a7-aef4-84cb998bb608) -> Local Result (bad)
![dude2-dressed](https://github.com/user-attachments/assets/8267bf26-3bde-47c2-b77b-dc65665f9561) -> Online Result (good)

What steps am i missing ? is this a models issues? can you provide some extra information about which models we should use?

**Comment by Zheng-Chong** [comment]
It seems your mask is not aligned with the expected ones. Try to produce the agnostic masks by modifying [provided script](https://github.com/Zheng-Chong/CatVTON/blob/edited/preprocess_agnostic_mask.py) to process your custom datasets.

**Comment by AI-P-K** [comment]
Hello, 

I have tried to use preprocess_agnostic_mask.py as you suggested, but now i am a bit confused.. this script looks for some structure that does not match with the structure i provide below. 

I am a little bit confused i thought all data that i need is already there, let me add more details to my use case:

The command i use for inference is:
python inference.py --dataset "vitonhd" --data_root_path "test_data/" --output_dir "output/"

The structure of my test_data is as follows:
1. agnostic-mask -> output of SCHP
2. cloth 
3. cloth-mask -> output of SCHP
4. image
5. image_parse-v3 -> output of CIHP_PGN
6. openpose_img -> output of OpenPose
7. openpose_json -> output of OpenPose

Can i kindly ask how did you figured that my mask is not aligned with the expected ones?

PS Thank you for your fast reply

**Comment by Zheng-Chong** [comment]
1. Your Mask is too close to the human body and does not match the shape of the target clothing, leading to shape issue. 
2. Your Mask eliminates hand information, making it difficult for the model to infer the posture, leading to no arms.
3. Local inference uses the model for 512X384, while the gradio app use 1024X768 model, leading to bad visual effects.

**Comment by AI-P-K** [comment]
Hello, 
1 and 2 you were correct... i have used the preprocess_agnostic_mask.py and now it dresses the model better. There is still some quality issues like a distorted face and sometimes, distorted clothing. 

![972dude2](https://github.com/user-attachments/assets/563a2c64-359d-47df-9092-57202fdb4346)

Do you suggest to change the local inference to 1024x768?

**Comment by AI-P-K** [comment]
So yes, i apologize for the stupid question. You were right with all the above, i appreciate your help and fast response. You have a fantastic day!

**Comment by AI-P-K** [comment]
p.s changing the inference resolution to 1024x768 locally solved the annomalies issues

**Comment by Zheng-Chong** [comment]
This depends on what your purpose for local inference is. If it's for generating a large number of high-quality results in parallel, 1024 would be better. If it's for calculating metrics, whether to use 512 or 1024 depends on the baseline you want to compare.

**Comment by Zheng-Chong** [comment]
I'm glad your  issues have been resolved 😄！
