### ISSUE TITLE
Online DEMO vs Local inference.py performance differences

### ISSUE THREAD

**Issue by AI-P-K** [Zheng-Chong/CatVTON#57]
I am trying to replicate the same performance i get from your online demo, by installing locally CatVTON repository. 

1. Inference parameters:
python inference.py --dataset 'vitonhd' --width 768 --height 1024

2. agnostik-mask -> SCHP to generate initial legs mask and  + preprocess_agnostic_mask.py
![dude2_mask](https://github.com/user-attachments/assets/5befb638-be15-4455-9eea-ead5ea64ae8d)

3. cloth-mask -> SCHP to generate mask
![3](https://github.com/user-attachments/assets/161b95d4-b986-4e2b-ad32-46c090261370)

4. image_parse-v3 -> CIHP_PGN
![dude2](https://github.com/user-attachments/assets/bb1276f7-8901-4aed-81e3-85ff8324ce4b)

5. openpose_img and openpose_json -> Openpose
![dude2_rendered](https://github.com/user-attachments/assets/884a527d-e1a3-4b20-823e-375c6c26e76c)
[dude2_keypoints.json](https://github.com/user-attachments/files/17029417/dude2_keypoints.json)

6. Original images
![dude2](https://github.com/user-attachments/assets/6bc300ec-e578-40d9-bff6-008a1385b8fd)
![3](https://github.com/user-attachments/assets/3725776c-662a-4985-9f7a-ebcbe19bd6dd)

7 Local Output:
![320dude2](https://github.com/user-attachments/assets/53ee2196-f743-4f01-aeaa-f66ab21bb728)

8. Online Output:
![converted](https://github.com/user-attachments/assets/ce564102-61ee-4211-adc1-337cdf749815)

Can i kindly ask where the differences in output are coming from?

**Comment by Zheng-Chong** [comment]
Due to the lack of clarity on what code modifications you have made, it is impossible to identify the source of the differences from the limited information available.
I suggest directly using Gradio to deploy the app for testing.
The purpose of Inference.py is to evaluate datasets and metrics, not for application development environments.

**Comment by AI-P-K** [comment]
I  did not do modifications to the code at all, i use exactly the repository provided. Using Gradio is not viable option for me.

**Comment by Zheng-Chong** [comment]
If the code is unmodified, `Inference.py` will not use the 1024 resolution model, even if specified through `--width 768 --height 1024`. This could be the reason for the different results. You can specify the use of the 1024 model in the code by setting the `version` parameter of `CatVTONPipeline` to `'mix'`.

**Comment by AI-P-K** [comment]
Once again you are correct... thank you for your help
