### ISSUE TITLE
人物图分辨率对色差的影响

### ISSUE THREAD

**Issue by chuanSir123** [Zheng-Chong/CatVTON#58]
1.首先用1024*1792去测试，很大概率衣服颜色是错的，蓝色变白色，黑色变白色。
2.再用1024*1024去测试，色差概率大大降低，而且不会蓝色变白色，会蓝色变浅蓝。
3.再用768*1024去测试，色差概率居中，有色差，而且不会蓝色变白色，会蓝色变浅浅蓝。

**Comment by Zheng-Chong** [comment]
目前模型只支持 768*1024，未在多分辨率数据下训练，其他分辨率理论上能正常推理但效果会比较差。
请问以上分辨率的测试是在什么情况下进行的？

**Comment by chuanSir123** [comment]
> 目前模型只支持 768*1024，未在多分辨率数据下训练，其他分辨率理论上能正常推理但效果会比较差。 请问以上分辨率的测试是在什么情况下进行的？

好的，之前没注意有分辨率限制，就直接comfyui传入全身图测试的（宽高比较小），请问衣服图片也是768*1024么~

**Comment by Zheng-Chong** [comment]
服装和人物输入的尺寸都是 宽 768x高 1024， ComfyUI 传入其他尺寸图像的会被裁剪和等比放缩到 768x1024， 输出的结果也是被裁剪的。

**Comment by chuanSir123** [comment]
> 服装和人物输入的尺寸都是 宽 768x高 1024， ComfyUI 传入其他尺寸图像的会被裁剪和等比放缩到 768x1024， 输出的结果也是被裁剪的。

噢噢，我使用的插件ComfyUI_CatVTON_Wrapper给我裁剪到了768*1400，我还是自己控制下768*1024吧~
