### ISSUE TITLE
We couldn't connect to..... 

### ISSUE THREAD

**Issue by gregcont** [Zheng-Chong/CatVTON#59]
![Screenshot 2024-09-23 015121](https://github.com/user-attachments/assets/5be176ff-f718-477b-ad86-380c0617433c)

We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like F:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\models\CatVTON\stable-diffusion-inpainting is not the path to a directory containing a scheduler_config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.

**Comment by Zheng-Chong** [comment]
This is caused by the delete of repo 'runaway/stable-diffusion-inpainting" in huggingface by RunawayML.
You can set ` "sd15_inpaint_path":  "booksforcharlie/stable-diffusion-inpainting“` in your ComfyUI to download from other repo.
Or download the new `ComfyUI-CatVTON.zip` from https://github.com/Zheng-Chong/CatVTON/releases/tag/ComfyUI to replace the old one.

**Comment by gregcont** [comment]
Do I change it in Extra_model_Paths.yml?

**Comment by Zheng-Chong** [comment]
In the ComfyUI App.
![image](https://github.com/user-attachments/assets/c9b40beb-1def-4582-b84b-e0fd7b7fc06b)

**Comment by gregcont** [comment]
![image](https://github.com/user-attachments/assets/46fc4ac3-63d5-4030-8974-b9ad7c040d9d)

Yeah But Manager won't let me install missing nodes.

**Comment by Zheng-Chong** [comment]
I suggest to reinstall following https://github.com/Zheng-Chong/CatVTON?tab=readme-ov-file#comfyui-workflow.

**Comment by glitzhigh** [comment]
Reinstalling is not working for me. Already tried on two different systems. I get missing nodes and can't seem to install them.

**Comment by Zheng-Chong** [comment]
This ComfyUI Node `CatVTON_Wrapper `is not maintained by this repository. Please raise the issue at https://github.com/chflame163/ComfyUI_CatVTON_Wrapper.
