### ISSUE TITLE
CatVTONWrapper

### ISSUE THREAD

**Issue by janersue555** [Zheng-Chong/CatVTON#61]
Encountering a new problem
CatVTONWrapper
We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like F:\Comfy UI\ComfyUI_windows_portable\ComfyUI\models\CatVTON\stable-diffusion-inpainting is not the path to a directory containing a scheduler_config.json file. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.

**Comment by Zheng-Chong** [comment]
CatVTONWrapper is not an official-supported project, it may need some update about the repo name in code to avoid this problem, you can raise this issue in its github repo. Or using the [ComfyUI app](https://github.com/Zheng-Chong/CatVTON/releases/tag/ComfyUI) provided in this repo.

**Comment by glitzhigh** [comment]
and what's the workaround for this problem please?

**Comment by Zheng-Chong** [comment]
This ComfyUI Node is not maintained by this repository. Please raise the issue at https://github.com/chflame163/ComfyUI_CatVTON_Wrapper .
