### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by faraztayari** [Zheng-Chong/CatVTON#64]
Everything looks fine, but after running the process, this error is shown: 

 error:  CUDA out of memory. Tried to allocate 18.00 GiB. GPU 0 has a total capacity of 8.00 GiB of which 3.08 GiB is free. Of the allocated memory 3.64 GiB is allocated by PyTorch, and 322.61 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management.

any idea how can i find the "batch_size"  and free up my vram. i have 1070 8GB

**Comment by Zheng-Chong** [comment]
8G video memory can only run under bf16 mixed precision, 1070 may not support

**Comment by faraztayari** [comment]
thanks, how can i change bf size to 16 in codes?

**Comment by Zheng-Chong** [comment]
From the information you provided, you may need to update your GPU to a more powerful one to run this project. The 1070 does not meet the minimum requirements to run.

**Comment by faraztayari** [comment]
thanks
