### ISSUE TITLE
LayerMask: Human Parts Ultra,lose efficacy??

### ISSUE THREAD

**Issue by yetao308** [Zheng-Chong/CatVTON#68]
LayerMask: Human Parts Ultra ， Invalid, how can I solve it?
The demand is to change the clothes on the model's body.
![Snipaste_2024-10-16_14-34-26](https://github.com/user-attachments/assets/023e462f-a900-4bbf-adf3-e3b9ec84ed93)

**Comment by Zheng-Chong** [comment]
This ComfyUI Node is not maintained by this repository. Please raise the issue at https://github.com/chflame163/ComfyUI_CatVTON_Wrapper .
