### ISSUE TITLE
preprocess_agnostic_mask 生成 mask 有许多有问题的mask 数据

### ISSUE THREAD

**Issue by Sheldongg** [Zheng-Chong/CatVTON#69]
请问使用这个脚本批量生成的mask 有许多有问题的数据，比如分割下装，会连带着上衣一块分割了。或者很多割裂的杂乱mask。
这种mask 数据需要经过人工筛查吗，还是作者也直接用这种数据进行训练的

**Comment by Zheng-Chong** [comment]
训练数据采用相同的 mask 生成程序，未进行人工筛选。
