### ISSUE TITLE
Comfyui无法加载节点

### ISSUE THREAD

**Issue by jasonlbx13** [Zheng-Chong/CatVTON#7]
When loading the graph, the following node types were not found:
        LoadAutoMasker
        CatVTON
        AutoMasker
        LoadCatVTONPipeline

**Comment by jasonlbx13** [comment]
找到原因了，应该是g++的问题

**Comment by Zheng-Chong** [comment]
Thanks for your attention, maybe you could describe your problem and solution in detail so that others can refer to it when they encounter the same problem?

**Comment by jasonlbx13** [comment]
因为我的服务器无法安装g++，所以遗憾的是并没有解决，建议这种项目尽量避免使用高度集成的库例如detectron2，涉及到编译会破坏原有环境导致很多问题
