### ISSUE TITLE
Lower inpaint not working

### ISSUE THREAD

**Issue by Elthibert** [Zheng-Chong/CatVTON#70]
I've tried everything, but i can't find a way to make the model swap pants part. Maybe i'm doing something wrong, but even with precise Segment anything masking + different image resolutions, the input pants image is not transfered in the masked image. But there is no problem for upper body part.

**Comment by Julietnacy** [comment]
@Elthibert That sounds frustrating! It might be a specific issue with the model you're using.I'll have to refer you to the official support live chat with the ticket ID NOD07638
Please see the link below to our dedicated support line:
[Node Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Elthibert** [comment]
well, after some trials it's seems to be due to my original image (the man is wearing a bomber jacket). But when i cange him by a naked upper body,, it works this time.

**Comment by Julietnacy** [comment]
@Elthibert okay
