### ISSUE TITLE
inference code for mask-free method will be released?

### ISSUE THREAD

**Issue by ApolloRay** [Zheng-Chong/CatVTON#71]

**Comment by Zheng-Chong** [comment]
The gradio app for mask-free version has been release in https://github.com/Zheng-Chong/CatVTON/blob/edited/app_p2p.py.

**Comment by ApolloRay** [comment]
> The gradio app for mask-free version has been release in https://github.com/Zheng-Chong/CatVTON/blob/edited/app_p2p.py.

我在huggingface上申请了模型的权限，麻烦通过一下，感谢。

**Comment by Zheng-Chong** [comment]
All eligible applications have been accepted.

**Comment by ApolloRay** [comment]
> All eligible applications have been accepted.

![截屏2024-10-22 16 39 04](https://github.com/user-attachments/assets/0e032608-4593-424f-b140-9b3113d6b307)

I can't Understand it ?

**Comment by Zheng-Chong** [comment]
This version of catvton is available for non-commercial scientific research purposes only. 
Only Institutional Email is acceptable.
