### ISSUE TITLE
About the first conv layer of UNet

### ISSUE THREAD

**Issue by qiuzidian** [Zheng-Chong/CatVTON#72]
Hello, according to the paper, the input latent channels for UNet is 8 but not 4? I would like to know how you deal with dimension mismatch. From the code, it seems that you only modified the attn layer? Could you help explain

**Comment by Zheng-Chong** [comment]
The first version on ArXiv contains some errors in the presentation of certain formulas. The number of input channels for the UNet model is 9. We are currently preparing the second version of the paper.

**Comment by qiuzidian** [comment]
您
