### ISSUE TITLE
How much time does the local generation on GPU can take?

### ISSUE THREAD

**Issue by VHornyi** [Zheng-Chong/CatVTON#86]
Hi, I have a question about the speed of this project. In the demo version on Hugging Face, one generation takes about 40 seconds. As I understand it, running locally on a machine with only a CPU is not possible or would take a very long time. So, I want to ask, when running locally on a powerful GPU, how much time does the generation of a result take?

**Comment by Zheng-Chong** [comment]
The speed depends heavily on the GPU you use. For powerful GPUs such as the RTX 4090, A100, or H100, it will take under 10 seconds locally.

**Comment by VHornyi** [comment]
> The speed depends heavily on the GPU you use. For powerful GPUs such as the RTX 4090, A100, or H100, it will take under 10 seconds locally.

Got it, thank you!
