### ISSUE TITLE
fatal: unable to access 'https://github.com/huggingface/diffusers.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.

### ISSUE THREAD

**Issue by LJX010204** [Zheng-Chong/CatVTON#91]
An error occurred while doing pip requirements.txt. Can I replace git+https://github.com/huggingface/diffusers.git with diffusers==0.29.2 like previous version?

**Comment by Zheng-Chong** [comment]
You can compile `diffusers` from source code by:
```
git clone https://github.com/huggingface/diffusers.git
cd diffusers
pip install -e .
```

**Comment by LJX010204** [comment]
Thanks！
