### ISSUE TITLE
Eval Result different from paper

### ISSUE THREAD

**Issue by ShenZheng2000** [Zheng-Chong/CatVTON#94]
I have verified the following:
1.  `--repaint` is used during inference
2. both prediction and groundtruth images has shape of 384x512.

## Paired VITON Evaluation

This is the evaluation command used for paired VITON:
```
CUDA_VISIBLE_DEVICES=0 python eval.py \
   --gt_folder /Datasets/zalando-hd-resized/test/image_512 \
   --pred_folder /Methods/CatVTON/results/vitonhd/vitonhd-512/paired \
   --paired \
   --batch_size=16 \
   --num_workers=16 
```

Result:
```
+-------------------+---------------------+--------------------+---------------------+
|        FID        |         KID         |        SSIM        |        LPIPS        |
+-------------------+---------------------+--------------------+---------------------+
| 5.453747499575712 | 0.43205747747748774 | 0.8739911913871765 | 0.05748799070715904 |
+-------------------+---------------------+--------------------+---------------------+
```

## Unpaired VITON Evaluation
This is the evaluation command used for unpaired VITON:
```
CUDA_VISIBLE_DEVICES=0 python eval.py \
    --gt_folder /Datasets/zalando-hd-resized/test/image_512 \
    --pred_folder /Methods/CatVTON/results/vitonhd/vitonhd-512/unpaired \
    --unpaired \
    --batch_size=16 \
    --num_workers=16 
```

Result:
```
+-------------------+--------------------+
|        FID        |        KID         |
+-------------------+--------------------+
| 9.069347879477675 | 1.1752656931931869 |
+-------------------+--------------------+
```

Could you please explain the reason for this discrepancy?

**Comment by Zheng-Chong** [comment]
Your reasoning results should be normal, as there is no significant difference compared to the reported metrics and outcomes.

The diffusion process inherently involves some randomness, which could be related to the selected random seed, software, or hardware environment. You may try using` different random seeds`, which can be directly specified in the parser.

Additionally, the reported metrics were obtained in the experimental environment. While the code in this repository has been refined to align as closely as possible with the experimental setup, slight variations may arise from modifications made to the code. This issue is also reported in https://github.com/Zheng-Chong/CatVTON/issues/10.

**Comment by ShenZheng2000** [comment]
Thanks for you detailed reply. I have a follow-up question.

I noticed that the predicted images from **IDM-VTON** has a height of 1024 (not 512). In this case, your evaluation code **resizes the ground truth images to match the predicted image height**. Could this be causing the issue?

## Paired VITON Evaluation for IDM-VTON
```
+-------------------+-------------------+--------------------+---------------------+
|        FID        |        KID        |        SSIM        |        LPIPS        |
+-------------------+-------------------+--------------------+---------------------+
| 8.224377077716525 | 3.654918658658644 | 0.8649349212646484 | 0.10005591064691544 |
+-------------------+-------------------+--------------------+---------------------+
```

## Unpaired VITON Evaluation for IDM-VTON
```
+--------------------+-------------------+
|        FID         |        KID        |
+--------------------+-------------------+
| 11.651678874460288 | 4.423769604604604 |
+--------------------+-------------------+
```

Perhaps I should set the height to 512 (maintaining the same height/width ratio) when running inference with IDM-VTON and then compare the results with the ground truth with a height of 512. Is this understanding correct?

**Comment by Zheng-Chong** [comment]
Resize 1024 results  to  512 and calculate the  metrics is not  a  fair way to compare with those methods based  on 512 inputs.
The results of IDM-VTON should also be generated  in  512x384 rather than 1024x768.

**Comment by ShenZheng2000** [comment]
Thanks.  However, I noticed that IDM-VTON's code does not support inference with 512x384 dimensions, only 1024x768. I have already raised a Github issue [here](https://github.com/yisol/IDM-VTON/issues/173) .  Could you please share how you addressed this shape issue and obtained the result for IDM-VTON (height of 512)?

**Comment by Zheng-Chong** [comment]
I asked the co-author responsible for the result calculation of IDM-VTON, and my previous response had an issue. 

> Resize 1024 results to 512 and calculate the metrics is not a fair way to compare with those methods based on 512 inputs. The results of IDM-VTON should also be generated in 512x384 rather than 1024x768.

We did **resize the IDM-VTON results from 1024 to 512, and then apply our metric calculation code.**

In theory, such a calculation should make IDM-VTON’s metrics higher than those of other methods, thus making IDM-VTON more favorable（means that for our method and other methods based on 512, the comparison could be disadvantageous) .

However, your result is significantly lower than the one reported in the paper. 
Did you manually resize the IDM-VTON results to 512 before calculating the metrics? If you directly use the 1024 results and calculate the metrics with the 512 GT, it may lead to inconsistent scales in the metrics.

**Comment by ShenZheng2000** [comment]
@Zheng-Chong I changed this [line](https://github.com/Zheng-Chong/CatVTON/blob/e8cc336657ba4a799c557bd680e099cecf9adc74/eval.py#L117) to reshape IDM-VTON prediction (result) instead of the groundtruth.
```
        if args.resize_pred:
            args.pred_folder = copy_resize_gt(args.pred_folder, gt_img.height)
        else:
            args.gt_folder = copy_resize_gt(args.gt_folder, img.height)
```

And the result of IDM-VTON is now better than reported in the paper. Is this expected?
```
Paired
+-------------------+--------------------+--------------------+--------------------+
|        FID        |        KID         |        SSIM        |       LPIPS        |
+-------------------+--------------------+--------------------+--------------------+
| 5.586475670132444 | 0.6270318093093238 | 0.8802446722984314 | 0.0717439129948616 |
+-------------------+--------------------+--------------------+--------------------+
Unpaired
+------------------+-------------------+
|       FID        |        KID        |
+------------------+-------------------+
| 8.73092843901128 | 0.973116066066068 |
+------------------+-------------------+
```

**Comment by Zheng-Chong** [comment]
The modified code doesn't seem to resize both the `pred_folder` and `gt_folder` to the same size. Additionally, `gt_img.height` and `img.height` are obtained by reading the first image from the `pred_folder` and `gt_folder`, so the changes you made might not work as expected. 
You may need to manually resize the predicted results to 512, rather than just modifying the evaluation code, as this could lead to unexpected issues.

**Comment by ShenZheng2000** [comment]
@Zheng-Chong 

I wrote a script to pre-resize the images as follows:

```
def resize_images_to_fixed_height(input_folder, output_folder, fixed_height=512):
    """
    Resize images to a fixed height while maintaining the original aspect ratio and save them to the output folder.

    Parameters:
        input_folder (str): Path to the folder containing the input images.
        output_folder (str): Path to the folder to save the resized images.
        fixed_height (int): The fixed height for resizing the images.
    """
    # Create the output folder if it doesn't exist
    os.makedirs(output_folder, exist_ok=True)

    # Get a list of all image files in the input folder
    image_files = [f for f in os.listdir(input_folder) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

    # Iterate over each image file and resize
    for file_name in tqdm(image_files, desc="Resizing images"):
        input_path = os.path.join(input_folder, file_name)
        output_path = os.path.join(output_folder, file_name)

        # Open the image
        with Image.open(input_path) as img:
            # Calculate the new width to maintain the aspect ratio
            original_width, original_height = img.size
            new_width = int((fixed_height / original_height) * original_width)

            # Resize the image
            resized_img = img.resize((new_width, fixed_height), Image.LANCZOS)

            # Save the resized image to the output folder
            resized_img.save(output_path)
```

Here are the scores I obtained when evaluating these reshaped predictions against the ground truth `image_512` (which already  has a height of 512)
```
Paired
+--------------------+--------------------+--------------------+--------------------+
|        FID         |        KID         |        SSIM        |       LPIPS        |
+--------------------+--------------------+--------------------+--------------------+
| 5.5649422137434215 | 0.5831380930931164 | 0.8668933510780334 | 0.0561465285718441 |
+--------------------+--------------------+--------------------+--------------------+
Unpaired
+-------------------+--------------------+
|        FID        |        KID         |
+-------------------+--------------------+
| 8.740116201420847 | 0.9322088713713902 |
+-------------------+--------------------+
```

Does the way I resize the images look correct to you? Interestingly, I noticed that the scores are still better than what was reported in the paper.

**Comment by Zheng-Chong** [comment]
This is indeed an interesting issue, but the processes seem to be consistent across the board. Your results and mine do show some differences. 

In some of the newer virtual try-on methods, such as[ Leffa](https://github.com/franciszzj/Leffa/tree/main) (Table 1) and [FiTDiT](https://github.com/BoyuanJiang/FitDiT) (Table 1), which compared to CatVTON, I have also found that OOTD or IDM outperform CatVTON on certain metrics. 

I will try to investigate the cause of these metric differences or the randomness involved in the future. Thank you for raising this issue. If you find the cause or  a more rigorous and standardized metric comparison method for unifying TryOn tasks, please let me know!
